#ifndef SETTINGS_PAGE_GLOBAL_H
#define SETTINGS_PAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETTINGS_PAGE_LIBRARY)
#  define SETTINGS_PAGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETTINGS_PAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGS_PAGE_GLOBAL_H
