#ifndef PROTOCOL_LIST_GLOBAL_H
#define PROTOCOL_LIST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOCOL_LIST_LIBRARY)
#  define PROTOCOL_LISTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROTOCOL_LISTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOCOL_LIST_GLOBAL_H
