#ifndef PROTOCOL_PROGRAM_GLOBAL_H
#define PROTOCOL_PROGRAM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOCOL_PROGRAM_LIBRARY)
#  define PROTOCOL_PROGRAMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROTOCOL_PROGRAMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOCOL_PROGRAM_GLOBAL_H
