#ifndef PROTOCOL_SAMPLES_GLOBAL_H
#define PROTOCOL_SAMPLES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOCOL_SAMPLES_LIBRARY)
#  define PROTOCOL_SAMPLESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROTOCOL_SAMPLESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOCOL_SAMPLES_GLOBAL_H
