#ifndef PROTOCOL_PAGE_GLOBAL_H
#define PROTOCOL_PAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOCOL_PAGE_LIBRARY)
#  define PROTOCOL_PAGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROTOCOL_PAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOCOL_PAGE_GLOBAL_H
